### PR TITLE
Text Color defines

### PR DESCRIPTION
**Pull request by Tmcg2**
Signed-off-by: Taggerung <tyler.taggerung@gmail.com>

### CODE REVIEW

**Comment by MegaMech** [comment]
I'm wondering if BGR should be written slightly differently.
Everyone recognizes RGB. Perhaps most coders are used to swapping the letters around?

What about: TEXT_COLOUR_CYCLE
or
TEXT_CYCLE_COLOURS ?

**Comment by Tmcg2** [comment]
I only chose BGR since super technically the cycle starts on Blue and then goes Green -> Red -> Blue, etc.
RGB is definitely the more common abbreviation and I'm not opposed to swapping it if desired.
I'm partial to having the colors of the cycle in the name since it doesn't cycle through all 4 colors, it (for some reason) leaves out yellow.

**Comment by MegaMech** [comment]
I'm leaning towards:
TEXT_BLUE_GREEN_RED_CYCLE_1
It's longer but the benefit is that its meaning is immediately clear.

Which PR should be merged first or does it not matter?

**Comment by Tmcg2** [comment]
Shouldn't matter, I did my best to make the independent of each other. I'll get to making the requested changes

**Pull request merged**
