### PR TITLE
Match func_8009A374

### PR DESCRIPTION
**Pull request by spazzylemons**
Overwriting the parameter variable was all that was needed to match this one

### CODE REVIEW

**Comment by Tmcg2** [comment]
Nice, this one has eluded me for a long time. Makes me wonder if `func_8009A478` can get rid of the fakematch with similar changes

**Comment by spazzylemons** [comment]
> Nice, this one has eluded me for a long time. Makes me wonder if `func_8009A478` can get rid of the fakematch with similar changes

@Tmcg2 turns out, yes! https://decomp.me/scratch/XAtLq I can add this to this PR if you'd like

**Comment by Tmcg2** [comment]
Sure, that would be great!

**Comment by spazzylemons** [comment]
Just pushed the func_8009A478 changes

**Comment by MegaMech** [comment]
Could you please delete the 2nd function.s file since you matched 2 functions?

**Comment by Tmcg2** [comment]
`func_8009A374`  is near identical to `func_8009A478`, and spazzylemon's way of matching `func_8009A374` turned out to fix the fakematch in `func_8009A478`. The .s file for `func_8009A478` ought to have been deleted months ago.

**Comment by MegaMech** [comment]
Just to clarify,

you're suggesting that there's 2 more .s function files that should be deleted?

**Comment by Tmcg2** [comment]
No, I'm saying the one file he did delete is the only file that needs deleting. The .s file for the other function was deleted months ago

**Comment by MegaMech** [comment]
OOoooh I get it now. Thanks!

**Pull request merged**
