### PR TITLE
Fix progress.py after euc-jp fix

### PR DESCRIPTION
**Pull request by MegaMech**
Addresses #345 

textconv taken from sm64. Likely used instead of iconv for portability.

### CODE REVIEW

**Comment by Tmcg2** [comment]
I was actually trying to accomplish the same thing recently, lol.
I've been trying to use `iconv` to do the conversion though

**Comment by MegaMech** [comment]
> I was actually trying to accomplish the same thing recently, lol. I've been trying to use `iconv` to do the conversion though

I think the progress.py percentage is off. But whatever.

**Comment by Tmcg2** [comment]
iconv is being difficult, I'll keep working on it if only to satisfy my own curiosity. If your stuff works I'd just go forward with it

**Comment by MegaMech** [comment]
Closing because #354 is a working solution.

**Pull request closed without merging**
