### PR TITLE
Update recomp.cpp

### PR DESCRIPTION
**Pull request by XDOneDude**
fixing for msys2 build

### CODE REVIEW

**Comment by MegaMech** [comment]
```
#if defined(_WIN32) || defined(_WIN64)
#include <capstone/capstone.h>
#else
#include <capstone.h>
#endif
```

**Comment by MegaMech** [comment]
Actually. Try this please

https://github.com/Emill/ido-static-recomp/pull/15

**Comment by Absoluc4s** [comment]
An alternative I use for building this is WSL which I'm able to build this perfectly on.

**Comment by MegaMech** [comment]
Abs, that's not relevant, this is about building on Windows. Linux already works

**Comment by MegaMech** [comment]
Closing because the PR is stale. I think the real solution is to update to the latest version of recomp

I've opened #315 so the issue doesn't get forgotten.

**Pull request closed without merging**
