### PR TITLE
Make adjustments to most course files

### PR DESCRIPTION
**Pull request by Tmcg2**
Move asset extraction to the new extract utility and included make files

Replace some integers with actual array/pointers.

### CODE REVIEW

**Comment by Tmcg2** [comment]
Don't know why the Jenkins build is having issues, could I get a hint?

**Comment by MegaMech** [comment]
```
n -woff 838,649 -signed -O2 -nostdinc -I include/libc -DTARGET_N64 -I include -I build/us -I build/us/include -I src -I . -DVERSION_US -mips2 -32 -DF3DEX_GBI -DF3D_OLD -D_LANGUAGE_C -o build/us/courses/battle/double_deck/packed.inc.o courses/battle/double_deck/packed.inc.c
python3 tools/set_o32abi_bit.py build/us/courses/staff_ghosts.inc.o
python3 tools/set_o32abi_bit.py build/us/courses/battle/double_deck/model.inc.o
tools/ido5.3_recomp/cc -c -Wab,-r4300_mul -non_shared -G 0 -Xcpluscomm -Xfullwarn -woff 838,649 -signed -O2 -nostdinc -I include/libc -DTARGET_N64 -I include -I build/us -I build/us/include -I src -I . -DVERSION_US -mips2 -32 -DF3DEX_GBI -DF3D_OLD -D_LANGUAGE_C -o build/us/courses/battle/skyscraper/model.inc.o courses/battle/skyscraper/model.inc.c
python3 tools/set_o32abi_bit.py build/us/courses/battle/double_deck/packed.inc.o
python3 tools/set_o32abi_bit.py build/us/courses/battle/skyscraper/model.inc.o
tools/ido5.3_recomp/cc -c -Wab,-r4300_mul -non_shared -G 0 -Xcpluscomm -Xfullwarn -woff 838,649 -signed -O2 -nostdinc -I include/libc -DTARGET_N64 -I include -I build/us -I build/us/include -I src -I . -DVERSION_US -mips2 -32 -DF3DEX_GBI -DF3D_OLD -D_LANGUAGE_C -o build/us/courses/battle/skyscraper/packed.inc.o courses/battle/skyscraper/packed.inc.c
tools/ido5.3_recomp/cc -c -Wab,-r4300_mul -non_shared -G 0 -Xcpluscomm -Xfullwarn -woff 838,649 -signed -O2 -nostdinc -I include/libc -DTARGET_N64 -I include -I build/us -I build/us/include -I src -I . -DVERSION_US -mips2 -32 -DF3DEX_GBI -DF3D_OLD -D_LANGUAGE_C -o build/us/courses/battle/big_donut/model.inc.o courses/battle/big_donut/model.inc.c
tools/ido5.3_recomp/cc -c -Wab,-r4300_mul -non_shared -G 0 -Xcpluscomm -Xfullwarn -woff 838,649 -signed -O2 -nostdinc -I include/libc -DTARGET_N64 -I include -I build/us -I build/us/include -I src -I . -DVERSION_US -mips2 -32 -DF3DEX_GBI -DF3D_OLD -D_LANGUAGE_C -o build/us/courses/battle/big_donut/packed.inc.o courses/battle/big_donut/packed.inc.c
cfe: Warning 568: No new-line character at the end of the file courses/battle/big_donut/packed.inc.c
python3 tools/set_o32abi_bit.py build/us/courses/battle/big_donut/model.inc.o
tools/ido5.3_recomp/cc -c -Wab,-r4300_mul -non_shared -G 0 -Xcpluscomm -Xfullwarn -woff 838,649 -signed -O2 -nostdinc -I include/libc -DTARGET_N64 -I include -I build/us -I build/us/include -I src -I . -DVERSION_US -mips2 -32 -DF3DEX_GBI -DF3D_OLD -D_LANGUAGE_C -o build/us/courses/battle/block_fort/model.inc.o courses/battle/block_fort/model.inc.c
python3 tools/set_o32abi_bit.py build/us/courses/battle/skyscraper/packed.inc.o
tools/ido5.3_recomp/cc -c -Wab,-r4300_mul -non_shared -G 0 -Xcpluscomm -Xfullwarn -woff 838,649 -signed -O2 -nostdinc -I include/libc -DTARGET_N64 -I include -I build/us -I build/us/include -I src -I . -DVERSION_US -mips2 -32 -DF3DEX_GBI -DF3D_OLD -D_LANGUAGE_C -o build/us/courses/battle/block_fort/packed.inc.o courses/battle/block_fort/packed.inc.c
python3 tools/set_o32abi_bit.py build/us/courses/battle/block_fort/model.inc.o
python3 tools/set_o32abi_bit.py build/us/courses/battle/big_donut/packed.inc.o
tools/n64graphics -i assets/courses/luigi_raceway/gTextureLuigiRacewaySignLeft.inc.c -g assets/courses/luigi_raceway/gTextureLuigiRacewaySignLeft.png -s u8 -f rgba16
tools/n64graphics -i assets/courses/luigi_raceway/gTextureLuigiRacewaySignRight.inc.c -g assets/courses/luigi_raceway/gTextureLuigiRacewaySignRight.png -s u8 -f rgba16
tools/n64graphics -i assets/courses/luigi_raceway/gTextureLuigiRacewayBalloonBasket.inc.c -g assets/courses/luigi_raceway/gTextureLuigiRacewayBalloonBasket.png -s u8 -f rgba16
tools/n64graphics -i assets/courses/luigi_raceway/gTextureLuigiRacewayBalloonRope.inc.c -g assets/courses/luigi_raceway/gTextureLuigiRacewayBalloonRope.png -s u8 -f rgba16
tools/ido5.3_recomp/cc -c -Wab,-r4300_mul -non_shared -G 0 -Xcpluscomm -Xfullwarn -woff 838,649 -signed -O2 -nostdinc -I include/libc -DTARGET_N64 -I include -I build/us -I build/us/include -I src -I . -DVERSION_US -mips2 -32 -DF3DEX_GBI -DF3D_OLD -D_LANGUAGE_C -o build/us/courses/mushroom_cup/luigi_raceway/model.inc.o courses/mushroom_cup/luigi_raceway/model.inc.c
python3 tools/set_o32abi_bit.py build/us/courses/battle/block_fort/packed.inc.o
python3 tools/set_o32abi_bit.py build/us/courses/mushroom_cup/luigi_raceway/model.inc.o
tools/n64graphics -i assets/courses/moo_moo_farm/gTLUTMole.inc.c -g assets/courses/moo_moo_farm/gTLUTMole.png -s u8 -f rgba16
tools/n64graphics -Z assets/courses/moo_moo_farm/gTextureMole1.inc.c -g assets/courses/moo_moo_farm/gTextureMole1.png -s u8 -f ci8 -c rgba16 -p assets/courses/moo_moo_farm/gTLUTMole.png
tools/n64graphics -Z assets/courses/moo_moo_farm/gTextureMole2.inc.c -g assets/courses/moo_moo_farm/gTextureMole2.png -s u8 -f ci8 -c rgba16 -p assets/courses/moo_moo_farm/gTLUTMole.png
tools/n64graphics -Z assets/courses/moo_moo_farm/gTextureMole3.inc.c -g assets/courses/moo_moo_farm/gTextureMole3.png -s u8 -f ci8 -c rgba16 -p assets/courses/moo_moo_farm/gTLUTMole.png
tools/n64graphics -Z assets/courses/moo_moo_farm/gTextureMole4.inc.c -g assets/courses/moo_moo_farm/gTextureMole4.png -s u8 -f ci8 -c rgba16 -p assets/courses/moo_moo_farm/gTLUTMole.png
tools/n64graphics -Z assets/courses/moo_moo_farm/gTextureMole5.inc.c -g assets/courses/moo_moo_farm/gTextureMole5.png -s u8 -f ci8 -c rgba16 -p assets/courses/moo_moo_farm/gTLUTMole.png
tools/n64graphics -Z assets/courses/moo_moo_farm/gTextureMole6.inc.c -g assets/courses/moo_moo_farm/gTextureMole6.png -s u8 -f ci8 -c rgba16 -p assets/courses/moo_moo_farm/gTLUTMole.png
tools/n64graphics -Z assets/courses/moo_moo_farm/gTextureMole7.inc.c -g assets/courses/moo_moo_farm/gTextureMole7.png -s u8 -f ci8 -c rgba16 -p assets/courses/moo_moo_farm/gTLUTMole.png
tools/n64graphics -i assets/courses/moo_moo_farm/gTLUTCowImport.inc.c -g assets/courses/moo_moo_farm/gTLUTCowImport.png -s u8 -f rgba16
tools/n64graphics -i assets/courses/moo_moo_farm/gTextureMooMooFarmDirt.inc.c -g assets/courses/moo_moo_farm/gTextureMooMooFarmDirt.png -s u8 -f rgba16
tools/ido5.3_recomp/cc -c -Wab,-r4300_mul -non_shared -G 0 -Xcpluscomm -Xfullwarn -woff 838,649 -signed -O2 -nostdinc -I include/libc -DTARGET_N64 -I include -I build/us -I build/us/include -I src -I . -DVERSION_US -mips2 -32 -DF3DEX_GBI -DF3D_OLD -D_LANGUAGE_C -o build/us/courses/mushroom_cup/moo_moo_farm/model.inc.o courses/mushroom_cup/moo_moo_farm/model.inc.c
python3 tools/set_o32abi_bit.py build/us/courses/mushroom_cup/moo_moo_farm/model.inc.o
tools/ido5.3_recomp/cc -c -Wab,-r4300_mul -non_shared -G 0 -Xcpluscomm -Xfullwarn -woff 838,649 -signed -O2 -nostdinc -I include/libc -DTARGET_N64 -I include -I build/us -I build/us/include -I src -I . -DVERSION_US -mips2 -32 -DF3DEX_GBI -DF3D_OLD -D_LANGUAGE_C -o build/us/courses/mushroom_cup/moo_moo_farm/packed.inc.o courses/mushroom_cup/moo_moo_farm/packed.inc.c
tools/ido5.3_recomp/cc -c -Wab,-r4300_mul -non_shared -G 0 -Xcpluscomm -Xfullwarn -woff 838,649 -signed -O2 -nostdinc -I include/libc -DTARGET_N64 -I include -I build/us -I build/us/include -I src -I . -DVERSION_US -mips2 -32 -DF3DEX_GBI -DF3D_OLD -D_LANGUAGE_C -o build/us/courses/mushroom_cup/kalimari_desert/model.inc.o courses/mushroom_cup/kalimari_desert/model.inc.c
tools/ido5.3_recomp/cc -c -Wab,-r4300_mul -non_shared -G 0 -Xcpluscomm -Xfullwarn -woff 838,649 -signed -O2 -nostdinc -I include/libc -DTARGET_N64 -I include -I build/us -I build/us/include -I src -I . -DVERSION_US -mips2 -32 -DF3DEX_GBI -DF3D_OLD -D_LANGUAGE_C -o build/us/courses/mushroom_cup/luigi_raceway/packed.inc.o courses/mushroom_cup/luigi_raceway/packed.inc.c
python3 tools/set_o32abi_bit.py build/us/courses/mushroom_cup/kalimari_desert/model.inc.o
tools/n64graphics -i assets/courses/kalimari_desert/gTextureCrossingSignalInactiveTopLeft.inc.c -g assets/courses/kalimari_desert/gTextureCrossingSignalInactiveTopLeft.png -s u8 -f rgba16
tools/n64graphics -i assets/courses/kalimari_desert/gTextureCrossingSignalInactiveTopRight.inc.c -g assets/courses/kalimari_desert/gTextureCrossingSignalInactiveTopRight.png -s u8 -f rgba16
tools/n64graphics -i assets/courses/kalimari_desert/gTextureCrossingSignalInactiveBottomLeft.inc.c -g assets/courses/kalimari_desert/gTextureCrossingSignalInactiveBottomLeft.png -s u8 -f rgba16
tools/n64graphics -i assets/courses/kalimari_desert/gTextureCrossingSignalInactiveBottomRight.inc.c -g assets/courses/kalimari_desert/gTextureCrossingSignalInactiveBottomRight.png -s u8 -f rgba16
tools/n64graphics -i assets/courses/kalimari_desert/gTextureCrossingSignalActiveTopLeft.inc.c -g assets/courses/kalimari_desert/gTextureCrossingSignalActiveTopLeft.png -s u8 -f rgba16
tools/n64graphics -i assets/courses/kalimari_desert/gTextureCrossingSignalActiveTopRight.inc.c -g assets/courses/kalimari_desert/gTextureCrossingSignalActiveTopRight.png -s u8 -f rgba16
tools/n64graphics -i assets/courses/kalimari_desert/gTextureCrossingSignalActiveBottomLeft.inc.c -g assets/courses/kalimari_desert/gTextureCrossingSignalActiveBottomLeft.png -s u8 -f rgba16
tools/n64graphics -i assets/courses/kalimari_desert/gTextureCrossingSignalActiveBottomRIght.inc.c -g assets/courses/kalimari_desert/gTextureCrossingSignalActiveBottomRIght.png -s u8 -f rgba16
Error loading "assets/courses/kalimari_desert/gTextureCrossingSignalActiveBottomRIght.png"
tools/ido5.3_recomp/cc -c -Wab,-r4300_mul -non_shared -G 0 -Xcpluscomm -Xfullwarn -woff 838,649 -signed -O2 -nostdinc -I include/libc -DTARGET_N64 -I include -I build/us -I build/us/include -I src -I . -DVERSION_US -mips2 -32 -DF3DEX_GBI -DF3D_OLD -D_LANGUAGE_C -o build/us/courses/mushroom_cup/kalimari_desert/packed.inc.o courses/mushroom_cup/kalimari_desert/packed.inc.c
make: *** [assets/include/courses/kalimari_desert.mk:48: assets/courses/kalimari_desert/gTextureCrossingSignalActiveBottomRIght.inc.c] Segmentation fault
make: *** Deleting file 'assets/courses/kalimari_desert/gTextureCrossingSignalActiveBottomRIght.inc.c'
make: *** Waiting for unfinished jobs....
python3 tools/set_o32abi_bit.py build/us/courses/mushroom_cup/moo_moo_farm/packed.inc.o
python3 tools/set_o32abi_bit.py build/us/courses/mushroom_cup/luigi_raceway/packed.inc.o
python3 tools/set_o32abi_bit.py build/us/courses/mushroom_cup/kalimari_desert/packed.inc.o
```

**Comment by MegaMech** [comment]
If I removed the cup folders would the .mk file handle being in the same folder as the src files?

ex.
courses/my_coursename/course_data.inc.c

**Comment by Tmcg2** [comment]
I'm not sure how my build was working, there WAS an issue in how one of the PNGs for Kalimari Desert was spelled.

I don't quite understand your question.

I could organize the `.mk` files into cup folders if you'd like, or I could move the `.mk` files into their respective `course` directory. Either way I'd have to change the expected output paths for some things but that's not a big deal. But, no the `course.inc.c` files shouldn't need to be moved.

**Comment by MegaMech** [comment]
One day in the future, I'd like to delete the cup folders and have everything use this directory structure:
`courses/course_name/course_data.inc.c`

I was just inquiring in-case that wouldn't work with the new extract assets system.

**Comment by Tmcg2** [comment]
Oh, yeah that would be fine. How the source files are organized shouldn't matter to the current asset extraction stuff, just as long as the source files have the correct paths for the  included stuff.

**Review by MegaMech — APPROVED** [review]

**Pull request merged**
