### PR TITLE
fixed permissions errors in IDO and extract_assets

### PR DESCRIPTION
**Pull request by farisawan-2000**
self-explanatory, I just copied over a working ido5.3 from another repo and it works (no deletions nor additions were made)

### CODE REVIEW

**Review by MegaMech — APPROVED** [review]
lgtm

**Comment by farisawan-2000** [comment]
turns out, some essential files weren't included

don't merge _just_ yet, since a pretty integral gitignore rule is guarding those

**Comment by farisawan-2000** [comment]
Ready for re-review!

**Comment by MegaMech** [comment]
It ok's now. Please merge

**Pull request merged**
